[notice]
title = "Beyond LIVE ─ 공지사항"
url = "https://beyondlive.com/notice?lang=ko"
entrySelector = "ul.notice-list li.notice-list__item"
titleSelector = "span.notice-list__title.notice-list__title"
linkSelector = "a.notice-list__link"
dateSelector = "notice-list__date"
dateFormat = "yyyy. MM. dd"
contentSelector = "span.notice-list__date"
waitUntil = "networkidle"

[contents]
title = "Beyond LIVE ─ 공연"
url = "https://beyondlive.com/contents?lang=ko"
entrySelector = "ul.list-grid li.list-grid__item"
titleSelector = "strong.list-grid__title"
linkSelector = "a.list-grid__link"
contentSelector = "span.artist__name"
imageSelector = "img.list-grid__img"
waitUntil = "networkidle"

[home]
title = "Beyond LIVE"
url = "https://beyondlive.com/"
entrySelector = "div.top-banner__slide-inner:not(.top-banner__slide swiper-slide swiper-slide-duplicate)"
titleSelector = "a.top-banner__title"
linkSelector = "a.top-banner__title"
contentSelector = "span.top-banner__date.shrink"
imageSelector = "div.top-banner__poster.shrink"
waitUntil = "networkidle"
