[notice]
title = "Beyond LIVE ─ 공지사항"
url = "https://beyondlive.com/notice?lang=ko"
entrySelector = "ul.notice-list li.notice-list__item"
titleSelector = "span.notice-list__title.notice-list__title"
linkSelector = "a.notice-list__link"
dateSelector = "notice-list__date"
dateFormat = "yyyy. MM. dd"
contentSelector = "span.notice-list__date"
waitUntil = "networkidle"

[contents]
title = "Beyond LIVE ─ 공연"
url = "https://beyondlive.com/contents?lang=ko"
entrySelector = "//html/body/div/main/section/div/ul/li/a"
titleSelector = "//concat(div[2]/strong[1]/text(), " | ", div[2]/p[1]/text())"
linkSelector = "//concat("https://beyondlive.com/contents/", translate(./@href, "javascript:moveViewPage();", ""))"
contentSelector = "span.artist__name"
imageSelector = "//div[1]/img[1]/@src"
waitUntil = "networkidle"

[contents_legacy]
title = "Beyond LIVE ─ 공연"
url = "https://beyondlive.com/contents?lang=ko"
entrySelector = "ul.list-grid li.list-grid__item"
titleSelector = "strong.list-grid__title"
linkSelector = "a.list-grid__link"
contentSelector = "span.artist__name"
imageSelector = "img.list-grid__img"
waitUntil = "networkidle"

[top]
title = "Beyond LIVE ─ TOP"
url = "https://beyondlive.com/?lang=ko"
entrySelector = "div.top-banner__slide-inner:not(.top-banner__slide.swiper-slide.swiper-slide-duplicate *)"
titleSelector = "a.top-banner__title"
linkSelector = "a.top-banner__title"
contentSelector = "span.top-banner__date.shrink"
imageSelector = "div.top-banner__poster.shrink"
waitUntil = "networkidle"

[next]
title = "Beyond LIVE ─ Beyond NEXT"
url = "https://beyondlive.com/?lang=ko"
entrySelector = "div.pickup-banner__inner.swiper-wrapper div.pickup-banner__slide:not(.pickup-banner__slide.swiper-slide.swiper-slide-duplicate)"
titleSelector = "em.pickup-banner__title"
linkSelector = "a.pickup-banner__link"
contentSelector = "span.pickup-banner__date"
imageSelector = "span.pickup-banner__img img"
waitUntil = "networkidle"
